version: '3.5'

services:
  fingerprint_engine:
    image: dahirmuhammaddahir/grpc_fingerprint_engine
    ports:
      - 4134:4134
    restart: unless-stopped
    container_name: fingerprint_engine
    networks:
      - fingerprint_engine_net
  
  fingerprint_client:
    image: r3y3s_fingerprint
    build: .
    ports:
      - 5555:80
    restart: unless-stopped
    container_name: r3y3s_fingerprint_client
    depends_on:
      - fingerprint_engine
    networks:
      - fingerprint_engine_net
      - fingerprint_client_net
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose: 
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - ../.env
  app:
    restart: always
    build: 
      context: ./
      dockerfile: app.Dockerfile
    command: yarn dev
    env_file:
      - ../.env
    ports:
      - 3000:3000
    expose:
      - 3306
    volumes:
      - "./app/:/usr/src/app/"
      - "/usr/src/app/node_modules"
networks:
  fingerprint_engine_net:
  fingerprint_client_net:

